# Generated by Django 5.1.4 on 2024-12-15 16:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_finder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productresult',
            name='image_url',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
